// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: grpc/org_sfomuseum_mobileclip.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EmbeddingsService_ComputeTextEmbeddings_FullMethodName  = "/org_sfomuseum_embeddings_service.EmbeddingsService/ComputeTextEmbeddings"
	EmbeddingsService_ComputeImageEmbeddings_FullMethodName = "/org_sfomuseum_embeddings_service.EmbeddingsService/ComputeImageEmbeddings"
)

// EmbeddingsServiceClient is the client API for EmbeddingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbeddingsServiceClient interface {
	ComputeTextEmbeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error)
	ComputeImageEmbeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error)
}

type embeddingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingsServiceClient(cc grpc.ClientConnInterface) EmbeddingsServiceClient {
	return &embeddingsServiceClient{cc}
}

func (c *embeddingsServiceClient) ComputeTextEmbeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error) {
	out := new(EmbeddingsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsService_ComputeTextEmbeddings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsServiceClient) ComputeImageEmbeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error) {
	out := new(EmbeddingsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsService_ComputeImageEmbeddings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingsServiceServer is the server API for EmbeddingsService service.
// All implementations must embed UnimplementedEmbeddingsServiceServer
// for forward compatibility
type EmbeddingsServiceServer interface {
	ComputeTextEmbeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error)
	ComputeImageEmbeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error)
	mustEmbedUnimplementedEmbeddingsServiceServer()
}

// UnimplementedEmbeddingsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmbeddingsServiceServer struct {
}

func (UnimplementedEmbeddingsServiceServer) ComputeTextEmbeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeTextEmbeddings not implemented")
}
func (UnimplementedEmbeddingsServiceServer) ComputeImageEmbeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeImageEmbeddings not implemented")
}
func (UnimplementedEmbeddingsServiceServer) mustEmbedUnimplementedEmbeddingsServiceServer() {}

// UnsafeEmbeddingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingsServiceServer will
// result in compilation errors.
type UnsafeEmbeddingsServiceServer interface {
	mustEmbedUnimplementedEmbeddingsServiceServer()
}

func RegisterEmbeddingsServiceServer(s grpc.ServiceRegistrar, srv EmbeddingsServiceServer) {
	s.RegisterService(&EmbeddingsService_ServiceDesc, srv)
}

func _EmbeddingsService_ComputeTextEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsServiceServer).ComputeTextEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsService_ComputeTextEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsServiceServer).ComputeTextEmbeddings(ctx, req.(*EmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsService_ComputeImageEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsServiceServer).ComputeImageEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsService_ComputeImageEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsServiceServer).ComputeImageEmbeddings(ctx, req.(*EmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingsService_ServiceDesc is the grpc.ServiceDesc for EmbeddingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org_sfomuseum_embeddings_service.EmbeddingsService",
	HandlerType: (*EmbeddingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeTextEmbeddings",
			Handler:    _EmbeddingsService_ComputeTextEmbeddings_Handler,
		},
		{
			MethodName: "ComputeImageEmbeddings",
			Handler:    _EmbeddingsService_ComputeImageEmbeddings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/org_sfomuseum_mobileclip.proto",
}
